"""Mandatory-channel-subscription check.

The bot must be an administrator of `REQUIRED_CHANNEL_ID` for `getChatMember` to be allowed
on a channel. If it is not (or the id is wrong), every check would raise — locking every
customer out of the shop — so configuration failures deliberately **fail open**: the user is
let through and the error is logged. Only a definitive "this user is not a member" answer
from Telegram closes the gate.
"""

from aiogram import Bot
from aiogram.enums import ChatMemberStatus
from aiogram.exceptions import TelegramAPIError, TelegramBadRequest
from redis.asyncio import Redis

from app.core.config import settings
from app.core.logging import get_logger

log = get_logger(__name__)

# Statuses that count as "subscribed". RESTRICTED is decided by its own `is_member` flag
# (a muted-but-present member is still a subscriber); LEFT/KICKED are not.
_MEMBER_STATUSES = frozenset(
    {
        ChatMemberStatus.CREATOR,
        ChatMemberStatus.ADMINISTRATOR,
        ChatMemberStatus.MEMBER,
    }
)

# Telegram's wording when the *user* is unknown to the channel, as opposed to the *bot*
# lacking access. Only this case is a real "not subscribed" verdict.
_USER_UNKNOWN_MARKERS = ("user not found", "participant_id_invalid", "user_id_invalid")

_CACHE_PREFIX = "subscribed:"
_CACHE_TTL_SECONDS = 300

# get_chat() result cached for the process lifetime — the channel's username/invite link is
# effectively static, and the gate is rendered on every blocked interaction.
_cached_channel_url: str | None = None


def is_gate_enabled() -> bool:
    return settings.required_channel_id is not None


async def is_subscribed(bot: Bot, telegram_id: int, redis: Redis | None = None) -> bool:
    """True if `telegram_id` is a member of the required channel (or the gate is disabled).

    Positive answers are cached in Redis for `_CACHE_TTL_SECONDS`; negative ones never are,
    so a user who has just joined is unblocked by their very next tap.
    """
    if not is_gate_enabled():
        return True

    cache_key = f"{_CACHE_PREFIX}{telegram_id}"
    if redis is not None and await redis.get(cache_key):
        return True

    try:
        member = await bot.get_chat_member(
            chat_id=settings.required_channel_id, user_id=telegram_id
        )
    except TelegramBadRequest as exc:
        if any(marker in str(exc).lower() for marker in _USER_UNKNOWN_MARKERS):
            return False
        log.error(
            "subscription_check_misconfigured",
            channel_id=settings.required_channel_id,
            telegram_id=telegram_id,
            error=str(exc),
        )
        return True
    except TelegramAPIError as exc:
        log.error(
            "subscription_check_failed",
            channel_id=settings.required_channel_id,
            telegram_id=telegram_id,
            error=str(exc),
        )
        return True

    if member.status == ChatMemberStatus.RESTRICTED:
        subscribed = bool(getattr(member, "is_member", False))
    else:
        subscribed = member.status in _MEMBER_STATUSES

    if subscribed and redis is not None:
        await redis.set(cache_key, "1", ex=_CACHE_TTL_SECONDS)
    return subscribed


async def forget_subscription(redis: Redis | None, telegram_id: int) -> None:
    """Drops the cached positive verdict so the next check hits Telegram again."""
    if redis is not None:
        await redis.delete(f"{_CACHE_PREFIX}{telegram_id}")


async def channel_url(bot: Bot) -> str | None:
    """Join link for the gate button: the configured override, else the channel's public
    @username, else an invite link generated by the bot (requires invite-users rights)."""
    global _cached_channel_url

    if settings.required_channel_url:
        return settings.required_channel_url
    if _cached_channel_url is not None:
        return _cached_channel_url
    if not is_gate_enabled():
        return None

    try:
        chat = await bot.get_chat(settings.required_channel_id)
    except TelegramAPIError as exc:
        log.error(
            "subscription_channel_lookup_failed",
            channel_id=settings.required_channel_id,
            error=str(exc),
        )
        return None

    if chat.username:
        _cached_channel_url = f"https://t.me/{chat.username}"
    elif chat.invite_link:
        _cached_channel_url = chat.invite_link
    else:
        try:
            _cached_channel_url = await bot.export_chat_invite_link(
                settings.required_channel_id
            )
        except TelegramAPIError as exc:
            log.error(
                "subscription_invite_link_failed",
                channel_id=settings.required_channel_id,
                error=str(exc),
            )
            return None
    return _cached_channel_url
