"""add payment providers and payment_transactions

Revision ID: 54d226ca08b4
Revises: 8742de301b8c
Create Date: 2026-08-03 21:02:00.161004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d226ca08b4'
down_revision: Union[str, None] = '8742de301b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New payment_method value must be committed before it can be used by any statement in a
    # later transaction (Postgres restriction on ALTER TYPE ... ADD VALUE).
    op.execute("ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'paynet'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('click', 'payme', 'paynet', name='payment_provider'), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('created', 'pending', 'paid', 'cancelled', 'failed', name='payment_tx_state'), server_default='created', nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_transactions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions')),
    sa.UniqueConstraint('provider', 'provider_transaction_id', name='uq_payment_tx_provider_tx_id')
    )
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_provider_transaction_id'), 'payment_transactions', ['provider_transaction_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_products_name_{uz,ru}_trgm — those trigram
    # indexes exist in the DB but aren't declared on the Product model/metadata, so they're
    # unrelated to this change and intentionally left alone here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_provider_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
    # Postgres has no ALTER TYPE ... DROP VALUE — removing 'paynet' from payment_method would
    # require rebuilding the enum type, which isn't done here to keep downgrade non-destructive.
